- metrics.py
- model.py
- qmodel.py
- quantize.py
- serialize.py
Thanks to advice from @Sopel97, implemented clipped relu for training, and that helped a huge amount.
The final missing piece was the scaling factor of 600 applied to the MSE loss.  And with that, we are getting reasonable evaluations finally!
> Clipped relu support

- nnue_dataset.py
- test_shared_library.py
- training_data_loader.cpp
Also add verification for halfkp features between cpp and py data loaders.
> Fix inverted `us` value from cpp data loader. 

- train.py
show filename of training and validation data
allow to set the number of torch threads
allow to set the batch size
> Add some additional arguments and output

- lib/nnue_training_data_formats.h
@Sopel97 please take a look, this fixes the warnings on clang - makes it much nicer to compile :).
> Fix warnings on clang

- train.py
--default_root_dir to specify a non-default log dir
--seed to specify a user controlled seed
> Additional command line arguments

- training_data_loader.cpp
fixes https://github.com/glinscott/nnue-pytorch/issues/18
> Make cdecl conditional on __x86_64__

- nnue_dataset.py
- train.py
- training_data_loader.cpp
--random-fen-skipping 5
Will skip on average 5 fens before accepting one.
With very large binpacks allows for more diversity in a batch/epoch, not using all moves of a game in that batch.
Randomness ensures that on repeated runs (or cycling) on the same binpack, all fens will eventually be used.
Little slowdown, especially with using --threads N --num-workers N,
even for large skipping values (e.g. skipping 10 -> 10% slowdown)
> Add --random-fen-skipping N

- feature_set.py
- halfkp.py
- nnue_bin_dataset.py
- train.py
The python data loader was broken by the last changes. We also want to return the features as tensors as it's more convenient.
> Make get_active_features return a tensor and make nnue_bin_dataset work again.

- model.py
current set of params that leads to the best net from scratch so far
https://tests.stockfishchess.org/tests/view/5ff40fc86019e097de3eee8f
(run 79).
> New params

- visualize.py
Some visualizer improvements:
- Address https://github.com/glinscott/nnue-pytorch/pull/39#issuecomment-753008644
- Support configurable colormap range vmin/vmax (abs values are plotted if vmin >= 0). Default values are -0.5/0.5.
- `--save-dir` option to directly store plots in a given directory
- `--dont-show` option to not show the plots (for e.g. non-interactive use)
- Minor visual/layout improvements (slightly smaller colorbar, other colormap, tighter layout).
Suggestions/comments welcome!
> Some visualizer improvements.

- serialize.py
just some statistics on clipped weights.
> Add info on clipped weights

- visualize.py
Too weak, too slow :)
I noticed a bug in the visualizer if `--order-input-neurons` is set. Now the L1 weights and input biases are also properly reordered.
Following up on the input biases optimization discussion, we might also consider optimizing a subset (e.g. 32) of the 256 input biases, assuming neurons with the highest weights norm are "more important". A reordered master net (ordered on L1 norm) looks like this:
> Bugfix in ordering of L1 weights + also order input biases.

- visualize.py
Several visualizer changes:
- Added king-centric input weights order via new argument `--input-weights-order`. This allows us to investigate some issues better, e.g. #53.
- `piece-centric-flipped-king` (default), as used currently, same as https://github.com/hxim/Stockfish-Evaluation-Guide
- `king-centric` (one block matrix per king position, for each piece position).
- Renamed `--order-input-neurons` to `--sort-input-neurons`
- Fix label for histogram in combination with `--input-weights-vmin >= 0` (then also abs(input weights) is shown).
Default:
With `--sort-input-neurons --input-weights-order=king-centric`:
> Add king-centric input weights order to visualizer.

- visualize.py
> Show info in input weights status bar on hover.

- run_games.py
Also, ctrl+c now works to stop run_games.py
Gives output like this:
```
Score of master vs logs/nn-epoch147.nnue: 13 - 7 - 29  [0.561] 49
Score of master vs logs/nn-epoch145.nnue: 11 - 0 - 18  [0.690] 29
```
> Add realtime results to run_games.py

- serialize.py
Fix NNUEReader that is broken after 401d25b7652a2a5c17897618225bbabd81ac8f03
> Fix broken NNUEReader.

- visualize.py
Arbitrary L2 and L3 were already supported, now also support arbitrary L1.
For the input weights plot, the ratio of the number of input neurons per row/col is chosen such that is as close to 4 (the current value for 256) as possible. This leads to the following aspect ratios for some likely candidates:
L1 | ratio
---- | ----
128 | 2
192 | 3
256 | 4
384 | 2.66...
512 | 2
Tested with a random 512x16x16 net (just change L1, L2, L3 in model.py):
> Support visualization of arbitrary number of input neurons.

- serialize.py
Complements 36de78f8729fe48f97fe81756ce65e2e5700e4c6
Amongst other things, fixes bogus output bias term in visualization if padding in L3 is present.
Now everything is in place to correctly visualize e.g. 512x16x16 nets :)
> Fix NNUEReader if SIMD weights padding is present.

- run_games.py
Useful when testing out new architectures.
> Add support for different binaries to run_games.py

- visualize.py
Speedup input weights visualization by precalculating masks for the first input neuron first.
Results are impressive. Simple bash timing with `time python visualize.py my_net.nnue --features="HalfKP" --save-dir=. --no-hist --no-biases --no-fc-weights --dont-show` reveals following wall-clock times.
num input neurons | master | this PR
---- | ---- | ----
256 | 28 s | 2.8 s
512 | 53 s | 3.0 s
> Speed up input weights visualization.

- ranger.py
Fixes #71.
I've also tried this in a recent test. No negative effect on elo vs current best pytorch nets: https://tests.stockfishchess.org/tests/view/6045af212433018de7a3864e
Original file here: https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer/blob/master/ranger/ranger2020.py
> Update ranger to 9/4/20 version

- do_plots.py
- move to argparse, by default only plot results close to optimal data so far (--elo_range=50 Elo or --loss_range=0.004 loss)
- provide a default output file name (--output=experiment_loss_elo.png)
- sort data from the tfevents files (useful if a run contains multiple restarts)
- increase resolution to 300dpi
> Refine plotting script

- model.py
Fixes the bug where BatchNorm is not being trained.
> Remove redundant module and grad check

- model.py
- ranger.py
> Bring back the old behavior for the GC being applied on the feature transformer weights.

- run_games.py
- train.py
just a few small changes
* checkpoint every 20 epochs
* provide --features argument to run_games.py
* check for existence of a .ckpt before the conversion, it might have been removed in the meanwhile
> Small changes

- visualize.py
The minor changes are:
- no input bias plot (can be added later but might need to be done in a new figure)
- biases use colormaps
- different labeling due to multiple subplots
> Update network visualization to the new architecture. Minor functional changes.

- docs/nnue.md
All hyperlinks works now.
Made small grammatical changes to sentences throughout the document.
> Fixed typos, hyperlinks, and improved readability

- model.py
Outcome loss should be against q, the net output.
> Fix outcome loss

- feature_set.py
Just so that it doesn't silently drift away from the reality in the future.
> Remove bucket selection on the python side as it was unused.

- docs/nnue.md
Recently I found out that a language can be specified near the code blocks to have syntax highlighting performed by github. Some editors like sublime text 3 also respect these "annotations". https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> Add syntax highlighting to code snippets in docs/nnue.md

- README.md
- features.py
- halfka_v2_hm.py
- model.py
- training_data_loader.cpp
See https://github.com/official-stockfish/Stockfish/pull/3646
The changes are:
- HalfKAv2_hm
- 1024x2-8-32-1
- lambda applied before the loss function (interpolate score and result)
- gamma=0.992
- LR=8.75e-4
- don't reduce LR for the last layer
> Update trainer for 2021-08-09 new master net

- cross_check_eval.py
Show min/max difference between evals.
Stockfish's `eval` format changed, support both.
> cross_check_eval.py improvements and updates.

- visualize.py
Since "_hm" normally has only half of the weights (for half of the king positions) it would look bad in the visualization and would be harder to make sense of, so we plot each weight twice, just like it would be used during play, to fill all 64 king squares.
> Update visualization to HalfKAv2_hm-1024x2-8-32-1

- LICENSE
Closes #151 
It was brought to attention that this reposity does not contain any license. It would make sense to license it with GPLv3, to match Stockfish, but if there are strong objections we can consider a different license. This better be done early as it requires an agreement from all authors.
I'd appreciate every pinged person to give a clear answer below.
> Add GPLv3 license notice.

- train.py
it was changed in some recent version of pytorch-lightning
relevant docs https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.model_checkpoint.html
> Change period into every_n_epochs

- model.py
- serialize.py
- train.py
This *should* be everything, but it would be best if the results were first replicated before merging. Also, not sure how to squash this, as there's a merge commit in between.
> SFNNv4 trainer

- model.py
- serialize.py
... to unify previously hardcoded numbers between model and serialize modules.
I think we should strive to have a single source of truth for everything model-related. Currently we need to keep an eye on the model and the serialized not to diverge. We will probably never get it fully defined in a single place but I think we should at least do what's feasible.
> Put quantization parameters in the model

- model.py
- serialize.py
@vondele could you please test quickly if this fixes the issue?
> Fix serialize/deserialize for SFNNv5

- scripts/easy_train.py
Since running a single experiment with multiple scripts doesn't make sense we don't need locking for the experiment. We do however need a lock for the workspace setup.
> Do a global lock and only for the parts that need it.

- run_games.py
somehow these transient errors are still seen
> Retry more, with a little pause

- run_games.py
explicitly pass a random seed to c-chess-cli
log the command
delete the intermediate pgn after appending.
rename or replace ordo file
> small run_games enhancements

- model.py
- train.py
this refines the loss function to the form used for the new master net in https://github.com/official-stockfish/Stockfish/pull/4100
The new loss function uses the expect game score to learn,
making the the learning more sensitive to those scores between loss and draw, draw and win.
Most visible for smaller values of the scaling parameter, but the current ones have been optimized.
it also introduces param_index for simpler explorations of paramers, i.e. simple parameter scans.
> Refined loss function

- nnue_dataset.py
- train.py
- training_data_loader.cpp
This will help to do some parameter scans in the data loader.
> Also pass param_index down to the data loader

- nnue_dataset.py
- train.py
- training_data_loader.cpp
convert the static value used in https://github.com/official-stockfish/Stockfish/pull/4314 into a parameter
would be cool if someone could test this since I have no idea how to run pytorch ^^
> introduce skip early plies parameter

- nnue_dataset.py
- train.py
- training_data_loader.cpp
a parameter was missing and also changed the default values to -1 since i think ply can be 0
> fix missing parameter

- docs/nnue.md
I've been using the `nnue.md` file to improve my own NNUE with quantization for some time now. It's been very helpful, but I've also found some issues, mostly with the optimized code. I've made a number of changes to the file which I split into independent commits, so I recommend reviewers to look at the individual commits (instead of all the changes simultaneously). Thank you for your time.
> Improve nnue.md documentation

- docs/nnue.md
The commit mainly fixes some typos but also contains some small fixes for the unoptimized NNUE implementation.
> Improve NNUE documentation

- docs/nnue.md
Alternative explanation to feature factorization, also explaining better why it's actually done.
> Improve NNUE documentation for feature factorization.

- model.py
- serialize.py
This was used to train a larger master net (nn-1b951f8b449d.nnue)
https://github.com/official-stockfish/Stockfish/pull/4646
> Increase L1 size to 2048 for training SFNNv7 nets

- train.py
Fixes error `AttributeError: 'Trainer' object has no attribute 'root_device'`
> Added missing .strategy

- docs/nnue.md
> Improving documentation

- model.py
To match SFNNv9: https://github.com/official-stockfish/Stockfish/pull/5149
> Increase L1 size to 3072

- scripts/easy_train.py
- scripts/easy_train_example.bat
- scripts/easy_train_example.sh
To match the recent new fishtest book
> Update default testing book to UHO_Lichess_4852_v1.epd.zip

- run_games.py
> [MINOR:TYPO] Update run_games.py

- train.py
another option that needed restoring somehow
> Introduce a fix for resuming form checkpoint

- feature_transformer.py
- train.py
master:
epoch 1: 21.43it/s
patch: 
epoch 1: 31.45it/s
> Use Torch Compile for the Model

- lib/nnue_training_data_formats.h
fixes https://github.com/official-stockfish/nnue-pytorch/issues/298
> Allow for readonly binpacks

- lib/nnue_training_data_formats.h
- lib/nnue_training_data_stream.h
Adds some includes which were previously transient
> Add Missing lib headers

- features.py
a bit messy for now todo this in the features code but easiest so far, untested but should work
> Allow dynamic l1 size

- feature_set.py
never had the _ in the name so guessing this never worked https://github.com/official-stockfish/nnue-pytorch/commit/75bc31e148fbc31cc2a8f62c1f3ef74e51111f32
> fix wrong function name

- lib/nnue_training_data_formats.h
- nnue_dataset.py
- train.py
- training_data_loader.cpp
as introduced by @linrock for training small nets, see e.g. https://github.com/official-stockfish/Stockfish/commit/cb4a62311985f685ba6f5457851527a3289073e6
https://github.com/linrock/nnue-pytorch/tree/128-skipSimpleEval-lt950-torch-compile
> Implement simple_eval_skipping

- dataloader_skip_config.py
- nnue_dataset.py
- train.py
- training_data_loader.cpp
Introduce a struct for this mess.
Implements https://github.com/official-stockfish/nnue-pytorch/pull/222#issuecomment-1368183732
> Abstract Dataloader Skip Config

- training_data_loader.cpp
fixes after for the benching of the data loader https://github.com/official-stockfish/nnue-pytorch/pull/326#issuecomment-3015265326
> Update Training Data Loader Bench

- cross_check_eval.py
- ftperm.py
- perf_sigmoid_fitter.py
Fixed: In `perf_sigmoid_fitter.py` `smart_fen_skipping` was also passed to the num_workers parameter instead of the filtered argument.
> Remaining config fixes

- train.py
it seems that pytorch-lightning will transfer the data to the correct device during training. might be useful to check if this would slow down training.
> Load data to CPU in training

- model.py
- requirements.txt
- scripts/easy_train.py
- train.py
Package got renamed a while ago.
Install `lightning` instead of `pytorch-lightning`
> Switch from pytorch_lightning to lightning

- model/lightning_module.py
gives some output that might be helpful to catch bugs
> Add loss to progress bar output

- data_loader/dataset.py
- docs/nnue.md
- model/callbacks.py
- model/feature_transformer.py
- model/features/__init__.py
- model/features/feature_block.py
- model/features/feature_set.py
- model/features/halfka.py
- model/features/halfka_v2.py
- model/features/halfka_v2_hm.py
- model/features/halfkp.py
- model/model.py
- model/utils/load_model.py
- model/utils/serialize.py
- scripts/easy_train.py
also cleans up legacy super calls
> More type hints

- train.py
Slightly more meaningful than just logdir
> Show actual log dir

- model/model.py
Idea suggested for FT factorizer by @jw1912 on discord. test this on layerstacks factorizer since the code is easier to work with
> Merge Factorizer on LayerStacks forward
