nnue_dataset.py
This PR fixes the bound return types for `create_stream` functions and argument types for `destroy_stream` and `fetch_next` functions. Previously they were incorrectly assumed to be ints - this bug only manifested on compiles where `sizeof(int) != sizeof(void*)`.
=> Fix incorrect ctypes pointer binding

lib/nnue_training_data_formats.h
this PR adds some code to the cpp data reader to skip positions where the (best)move is a capture or the position is in Check. 
Removing these positions from training data significantly improved results  in testing. 
While we can gensfen positions that satisfy these constraints, having it in the reader should make it easier to use data from other sources (fishtest)
@Sopel97 has ideas for a follow-up clean-up (i.e. pass a filter function instead of coding it at this low level).
=> Skip inCheck or capturing bestmoves

lib/nnue_training_data_formats.h, lib/nnue_training_data_stream.h, nnue_dataset.py, train.py, training_data_loader.cpp
Refactor position skipping to be easier to configure, more centralize…d, togglable by cli argument, and work for .bin. Add --smart-fen-skipping option (flag) that mimicks nodchip trainer option with the same name, default to false.
For parallel binpack loader the filtering happens in the worker threads during reading the binpack file. For non-parallel binpack reader and for bin readers the filtering happens at stream level. The predicate for skipping is configurable before stream construction. Filtering is dynamically togglable from python side.
Note that the python data loader still does not handle this option.
=> Refactor filtering.

README.md, halfkp.py, model.py, nnue_bin_dataset.py, scripts/train.sh, serialize.py, train.py
@vondele @Sopel97 
train.py
- Adds `--enable-factorizer` option.  Default is false, which will train without factorizer.  Factorizer on or off dynamically modifies the model shape, so you can resume non-factorized nets in factorizer mode.
- Adds `--reuse-from-model` option.  Pass in a serialized model, ending in `.pt`, to resume from those weights.
serialize.py: 
- Fixes nnue -> pt, as they need to be imported without factorizer shapes.
- Supports both factorized and non-factorized pt -> nnue conversions.
=> Cleanup model import/export with factorizer

halfkp.py, nnue_dataset.py, training_data_loader.cpp
This PR adds value arrays in the sparse batch that stand for the feature count. Now all features for a single position should have unique indices, but may have different counts (weights).
This is untested, please verify that there are no obvious mistakes.
=> Pass feature counts and remove the magic `20` constant for halfk factorizer.

nnue_dataset.py, train.py, training_data_loader.cpp
If nothing significant changed this has the same effect as the previous draft:
vondele's tests
```
master: 634fd18a5617ded20e6e187336a28cc4084741a
18.54it/s  76% load
ensure_coalesced_2:
python train.py --smart-fen-skipping --batch-size 16384 --threads 8 --num-workers 4 --gpus "0,"
25.6 it/s
```
@vondele could you please verify that this is still better?
=> Optimize training

lib/nnue_training_data_formats.h
shuffles the fens before use, increase the buffer used for reading
speed essentially unchanged (18.9 -> 18.8 ?) and slight increase in resident memory (3.5 -> 4.2G)
=> shuffle fen reading buffer before use

lib/nnue_training_data_formats.h, lib/rng.h, training_data_loader.cpp
This should be non-function apart from the rng change. This ensures only one rng per thread is created. Also the skipPredicate doesn't instantiate variables related to random skipping if it's not used.
=> Only instantiate a single rng per thread. More laziness in skipPredicate.

README.md, docs/features.md, feature_block.py, feature_set.py, features.py, halfkp.py, model.py, serialize.py, train.py, training_data_loader.cpp
This PR introduces a more robust and extensible abstraction for features (for now only on the python side).
A feature transformer is defined over a `feature_set`. A `feature_set` is a list of `feature_block`s. Each `feature_block` contains a name, hash, num_real_features, num_virtual_features, num_features, and knows some stuff about how to manipulate its indices. The number of real features and virtual features is used to distinguish factorizers, because they have to be handled differently on serialization to .nnue. A `feature_block` consists of `factors` which are an `OrderedDict` of `(str, int)` pairs where the first is the name of the factor and the second is its size. The first factor is assumed to be real, all the following ones are assumed to be virtual. `feature_set` concatenates …
=> A better abstraction for features on the python side.

cross_check_eval.py
This tool allows checking whether the pytorch model and stockfish match in position evaluation.
```
usage: cross_check_eval.py [-h] [--net NET] [--engine ENGINE] [--data DATA]
[--count COUNT] [--features FEATURES]
optional arguments:
-h, --help           show this help message and exit
--net NET            path to a .nnue net
--engine ENGINE      path to stockfish
--data DATA          path to .bin dataset
--count COUNT        number of datapoints to process
--features FEATURES  The feature set to use. Can be a union of feature
blocks (for example P+HalfKP). "^" denotes a factorized
block. Currently available feature blocks are: HalfKP,
HalfKP^
```
Currently it works purely on the python side, so the data must be in .bin format. The python data loader is useful again :).
The `--features` …
=> Add a tool for checking nnue eval correlation between the model and the stockfish engine.

model.py
yields best net so far.
https://tests.stockfishchess.org/tests/view/5fef930f6019e097de3eeb84
using gensfen data:
https://drive.google.com/file/d/1VlhnHL8f-20AXhGkILujnNXHwy9T-MQw/view?usp=sharing
=> Add stepLR scheduler, adjust default ranger betas

README.md, visualize.py
This is a cleanup of the script in https://github.com/official-stockfish/Stockfish/issues/3274, extended to work on pytorch models (such that also checkpoints can be loaded).
At the moment, abs(input weights) is plotted (in the same style as the base script, but now normalized between 0 and 0.5).
Note that this is a "minimal working example". Please suggest if there is any need/wish to extend it with CLI arguments to e.g.
- Save plots directly to images (non-interactive mode for headless/automated use case).
- Control some parameters (saturation threshold that is now arbitrarily at 0.5; provide the option to plot non-abs values).
- Other useful plots?
- ...
=> Add visualizer.

features.py, halfka.py, halfkp.py, serialize.py, training_data_loader.cpp
This PR adds `HalfKA` and `HalfKA^` feature blocks.
The stockfish binary that can be used for playing (on nodchip because I couldn't be bothered with the official-stockfish): https://github.com/Sopel97/Stockfish/tree/flip_halfka
Note: This PR fixes the serialization and deserialization of the FT hash. Now the hash exposed by the feature class matches the hash in nodchip (previously it was ^512, which should be done later). This breaks .pt/.ckpt -> .nnue conversion of old models (but can be hacked by forcing model.feature_set in the code to be different, it just loads the old one from the checkpoint)
=> Add support for (flip) HalfKA features

visualize.py
retain viridis for 'one-sided' visualization, use a diverging one for 2-side vis.
A two-sided one now looks like:
BTW, the fact that these weights look so symmetric with opposite sign, I'm wondering if we should initialize them similarly, i.e. as we do now, copy and invert those random numbers on the matching patches. Maybe there are other ways we could exploit this (like compress nets or so).
=> Improved cmaps

visualize.py
This a cleanup version of of the code used in #47, with the following additions/improvements:
- Heatmap visualization of the weights in the final three layers.
- Histogram plots of the weights in the first and second fully-connected layers.
- Added argument `--order-input-neurons` to order the input neurons based on the L1-norm (sum of absolute values) of their connected weights. This norm seemed most "visually pleasing" (I also tested L2-norm and L_infinity-norm (max abs norm), but didn't like them).
- Changed default vmin/vmax for input weights to -1/+1, as this seems more logical and saner for most of the nets that are currently generated in the training runs.
- Add prefix for saved files (default = net name), can be overriden with `--save-prefix`.
Sample outputs:
Suggestions are …
=> Add visualization for weights of final layers.

README.md, model.py
lead to best net so far (run84/run3/epoch 245)
https://tests.stockfishchess.org/tests/view/600d41d7735dd7f0f0352c2d -15 Elo vs master
https://tests.stockfishchess.org/tests/view/600d42db735dd7f0f0352c2f  -3 Elo vs SV
trainer invoked as
```
python train.py --smart-fen-skipping --random-fen-skipping 10 --batch-size 16384 --threads 8 --num-workers 8 --gpus 1  large_gensfen_multipvdiff_100_d9.binpack large_gensfen_multipvdiff_100_d9.binpack
```
and run for > 200 epochs
=> Use a reduced learning rate for the output layer.

visualize.py
Some visualizer improvements:
- Introduce `--input-weights-auto-scale` and `fc-weights-auto-scale` to be able to better investigate clipping in color maps.
- Add histogram for input weights.
- Log scale for all histograms + make sure we don't miss any outliers (e.g. handy for unquantized checkpoints).
- Add plot for all biases.
- Introduce options `--no-input-weights`, `--no-fc-weights`, `--no-biases`, `no-hist` to selectively omit generation of plots  (e.g. `--no-input-weights` now leads to very fast generation as no time-consuming input layer processing is needed anymore).
- Introduce options `--default-width` and `default-height` to set the default plot size in pixels (default: 1600x900). Can be very handy to generate ultra-high resolution (lossless) images.
- Refactoring (e.g. of …
=> Visualizer improvements

README.md, visualize.py
Add support to visualize the difference between two models (can be .cpkt, .pt or .nnue, both of mixed type is supported):
- New optional `--ref-model` argument.
- New optional `--ref-features` argument (default = source model features).
- Renamed `--net-name` to `--label`.
Example 1: visualize the difference between vondele `run84run3/epoch=427.ckpt` and `run84run3/epoch=245.ckpt`. Contrary to what I was thinking earlier, there are quite some differences between the two checkpoints.
```
python visualize.py ../research/run84run3/epoch=427.ckpt --features="HalfKP^" --ref-model ../research/run84run3/epoch=245.ckpt --input-weights-auto-scale --fc-weights-auto-scale --save-dir=.
```
Example 2: difference between master net nn-62ef826d1a6d.nnue and latest default net from SV run …
=> Visualize difference between two models.

visualize.py
Sorry, was too hasty in previous PR and didn't check the case if `--order-input-neurons` is not set.
It just crashes right now in that case:
`AttributeError: 'NNUEVisualizer' object has no attribute 'ordered_input_neurons'`
=> Fix script if --order-input-neurons not set.

model.py
The weight shape of torch.nn.Linear is (out, in) ([source](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear)).
In the case of HalfKP^, `print(a, b, weights.shape)` produces `41024 41728 torch.Size([256, 41728])`.
=> Fix virtual feature initialization

model.py, qmodel.py
Some versions of pytorch disallow this in-place operation with grad.
=> Use torch.no_grad() when zeroing virtual feature weights. 

perf_sigmoid_fitter.py
This script finds the sigmoid scaling that matches the provided data. The sigmoid scaling is the coefficient k in sigmoid(eval*k) such that the resulting value matches the perf% derived from scores and outcomes.
This script can be used as a standalone tool by calling it with a filename as an argument (no arguments to see help); or as a module in which case it can be used to compute the correct sigmoid scaling for a training batch.
In its current state it might be too slow to use for each batch, but it still might be incorporated somehow.
=> Add a perf_sigmoid_fitter.py script

do_plots.py
Usage: `python do_plots.py out_file.png root_dir0 [root_dir1] [root_dir2] ...`
`root_dir`s are searched for:
1. tfevents file
2. ordo.out
`val_loss` and `train_loss` is extracted from tfevents file. If more than one value per step was found in the given `root_dir` (for example if there are multiple ftevents files) the best value is taken for plotting.
if `ordo.out` exists (otherwise it's not used) it is parsed and the best result for each epoch is used for plotting the elo.
example output:
=> Add a script for plotting loss and ordo elos.

delete_bad_nets.py
Directly from help:
```
Usage: python delete_bad_nets.py root_dir [num_best_to_keep]
root_dir - the directory to "cleanup"
num_best_to_keep - the number of best nets to keep. Default: 16
It expects to find ordo.out somewhere within root_dir.
If the ordo.out is not found nothing is deleted.
It uses the ratings from the ordo file to determine which nets are best.
The engine names must contain the network name in the
following format: "nn-epoch[0-9]*\.nnue". The network file
can be specified with a parent directory (for example
"run_0/nn-epoch100.nnue"), in which case the .ckpt file corresponding
to this .nnue file will only be searched for in the parent ("run_0") directory.
The .ckpt files must contain "epoch=([0-9]*).*\.ckpt".
Both ckpt and nnue files are deleted. Only nets listed in the …
```
=> Add a script for deleting worst nets within a directory based on ordo.

cross_check_eval.py, nnue_dataset.py, training_data_loader.cpp
Thich means that there's no need to implement the feature transformer index generation in python code. This is particularily important for new feature blocks. Before this the features had to be generated in 3 places - data loader, player, trainer. Now the trainer never needs to know the feature indices.
I also might become useful for other things. The newly added function is `nnue_dataset.make_sparse_batch_from_fens`, which takes a feature set, list of fens, list of scores, list of ply numbers, and a list of results (in -1, 0, 1 form). Currently for each position some legal move is generated, as it doesn't really matter, but in the future the move could also be passed as an argument.
=> Make cross_eval_check script form batches from fens, delegated to the data loader.

README.md, cross_check_eval.py, feature_transformer.py, model.py, nnue_dataset.py, serialize.py, training_data_loader.cpp
This PR introduces a semi-sparse matrix multiplication with dense matrix kernel. "Semi-sparse" because the indices are stored in a 2d array, with the first dimension being the position id, and the values being the row. To use the kernel [cupy](https://cupy.dev/) must be installed. It doesn't bundle cuda libraries like pytorch does so it might require a separate installation for matching cuda. The version used *might* need to match the version used by pytorch. To check the cuda version pytorch uses run `torch.version.cuda`
To be precise, there are 2 output slices for the feature transformer. Each slice corresponds to one perspective (white, black). The input is a semi-sparse matrix being represented by `indices` and `values`. The `indices` is a int32 matrix of shape `(batch_size, …
=> A custom kernel for the feature transformer.

README.md, cross_check_eval.py, feature_set.py, features.py, halfka.py, halfka_v2.py, halfkp.py, model.py, nnue_bin_dataset.py, nnue_dataset.py, perf_sigmoid_fitter.py, ranger.py, serialize.py, train.py, training_data_loader.cpp, visualize.py
This is a slightly cleaned up version of https://github.com/Sopel97/nnue-pytorch/tree/experiment_56, with a few changes:
- weight clipping is moved outside of the optimizer, should behave about the same
- updated visualize.py to at least work, though it doesn't visualize fc layers and the plot for ft weights is slightly off
- updated cross_eval_check.py
- updated perf_sigmoid_fitter.py
- changed LR scheduling based on further results
Now will follow results from individual changes. The separate graphs are not comparable between each other.
- weight clipping 
- per psqt features 
- 8 subnets and psqt buckets 
- MSE over WDL-space evals (not very visible on the graph, but the trend was 3 elo better. Loss not comparable)
- disable GC (lower loss)
- drop LR by 0.987 every epoch (trend ~2 elo …
=> Update trainer to the new architecture.

training_data_loader.cpp
Non-functional, but might be relevant in the future. The value is currently unused.
=> Fix the reported size of the HalfKAv2Factorized feature set.

visualize_multi_hist.py
NOTE: I'm taking suggestions for the script file name.
One net per row. Multiple nets can be passed. Currently plotted histograms:
- Feature transformer weights (input_weights_hist.png)
- Feature transformer PSQT weights (in actual stockfish internal units) (input_weights_psqt_hist.png)
- L1 (one subnet per column) (l1_weights_hist.png)
- L2 (one subnet per column) (l2_weights_hist.png)
- output (one subnet per column) (output_weights_hist.png)
Example plots:
```
C:\dev\nnue-pytorch>python visualize_multi_hist.py --features=HalfKAv2 W:\nnue\nnue-pytorch-training\nn-exp57-run7-epoch399.nnue W:\nnue\nnue-pytorch-training\nn-exp58-run3-epoch359.nnue W:\nnue\nnue-pytorch-training\nn-exp59-run0-epoch319.nnue W:\nnue\nnue-pytorch-training\nn-exp66-run0-epoch239.nnue
```
=> Visualization of weight histograms among many networks.

train.py
This fixes an issue where some part of the model was always allocated to the default cuda device and then a copy of it would reside there taking up memory. This was only impacting multi-gpu setups.
=> Fix model leftovers on the default cuda device.

lib/nnue_training_data_formats.h, nnue_dataset.py, train.py, training_data_loader.cpp
this intends to skip (or more correctly weight) data points that are possibly incorrectly evaluated, i.e. retain data that are more likely to be correct.
Was used to train two recent SF nets:
https://github.com/official-stockfish/Stockfish/pull/3816
https://github.com/official-stockfish/Stockfish/pull/3808
--no-wld-fen-skipping option can be used to disable the default
=> Introduce skipping based on the likelihood of the game outcome

feature_set.py, model.py
This patch decouples bucketing scheme from the feature set definition on the python side (which didn't make much sense) and allows it to be specified in the constructor of the model. There is no way to verify consistency with the data loader so of course the number of buckets must match the number expected by the data loader. Also fixes a small bug where `self.num_psqt_buckets` was not respected in a few places.
=> Easy parametrization of PSQT and layer stack buckets.

training_data_loader.cpp
skips positions to target a prescribed distribution of positions with number of pieces.
Uses i*(32-i)/(16*16)+1
Introduces a max skipping factor of 15.
Needs some further work to make this optional and more flexible.
=> Skip positions to target a distribution

lib/nnue_training_data_formats.h
Spotted recently. Utilization depended on skipping because we used an indepndent counter instead of buffer size. This might impact other performance issues.
=> Fix binpack reader thread buffer utilization.

model.py
lead to a slightly stronger net https://tests.stockfishchess.org/tests/view/62ce5f421dacb46e4d5fd277
=> refine loss function power

serialize.py
It seems that an incorrect weight scale for output fc layers is used in NNUEReader, which causes a broken pt converted from a nnue file:
https://github.com/glinscott/nnue-pytorch/blob/77d79192877513878adc38aa4a3e9ce681be5f7f/serialize.py#L193-L195
According to NNUEWriter, this should be: 
https://github.com/glinscott/nnue-pytorch/blob/77d79192877513878adc38aa4a3e9ce681be5f7f/serialize.py#L102-L109
=> Fix the incorrect weight scale used in NNUEReader

training_data_loader.cpp
Fixed the incorrect NUM_PT bug, as mentioned by @Pikacat-OuO in SF discord [here](https://discord.com/channels/435943710472011776/733545871911813221/1029376219415851018).
=> Fix the incorrect NUM_PT in HalfKAv2_hmFactorized

run_games.py
Improves readability by aligning the text in each row with table headers. Numbers are right-aligned to line up the decimals. Player names are left-aligned. Table parsing works the same as before since only whitespace was modified and the text is all the same.
Before:
```
1 run_6/nn-epoch539.nnue : 1.7 5.4 2713.5 5400 50
2 run_5/nn-epoch579.nnue : 0.7 6.7 1803.5 3600 50
3 master : 0.0 ---- 722906.5 1384200 52
4 run_11/nn-epoch559.nnue : -0.3 5.4 2698.0 5400 50
5 run_5/nn-epoch499.nnue : -0.9 4.7 3590.5 7200 50
```
After:
```
1 master                     :     0.0   ----   55579.0  103680   54
2 run_0/nn-epoch219.nnue     :   -12.7    5.3    2775.0    5760   48
3 run_0/nn-epoch239.nnue     :   -13.3    7.5    1385.0    2880   48
4 run_0/nn-epoch179.nnue     :   -17.0    3.7    5479.0 …
```
=> Align column text when writing ordo tables to improve readability

scripts/easy_train.py
camelCase methods in threading were deprecated in: https://github.com/python/cpython/pull/25174
```
easy_train.py:316: DeprecationWarning: setDaemon() is deprecated,
set the daemon attribute instead thread.setDaemon(True)
```
=> Fix warnings about thread.setDaemon() in python 3.10+

training_data_loader.cpp
With the recent new network for Stockfish it appears that we need to do some more costly filtering on the datasets (https://github.com/official-stockfish/Stockfish/pull/4295). Removing positions from the dataset degrades compression, so in some cases it might be better to mark positions with a special flag and skip them on load. I think it's reasonable to use `score==VALUE_NONE` as such a flag and this PR implements it.
=> Skip positions with score equal to Stockfish's VALUE_NONE (32002)

train.py
Fixes a crash upon training start when newer versions of pytorch-lightning are used due to `Trainer.root_gpu` being removed in 1.8+ a few weeks ago.
```
AttributeError: `Trainer.root_gpu` was deprecated in v1.6 and is no longer
accessible as of v1.8. Please use `Trainer.strategy.root_device.index` instead.
```
Support for `Trainer.root_gpu` was removed in:
https://github.com/Lightning-AI/lightning/issues/11994
More info about pytorch-lightning 1.8.0 in the release notes:
https://github.com/Lightning-AI/lightning/releases/tag/1.8.0
Fixes https://github.com/glinscott/nnue-pytorch/issues/212
=> Fix Trainer.root_gpu crash when using pytorch-lightning 1.8+

scripts/easy_train.py
Add support for the `--early-fen-skipping` param introduced in https://github.com/glinscott/nnue-pytorch/pull/222 to `easy_train.py`. This can be used to skip all positions where the ply count is less than or equal to the given number during training.
=> Enable using early fen skipping param with easy_train.py

docs/nnue.md
The new "SFNNv6" architecture is missing in the table of contents, so update it to reflect the new NNUE architecture.
=> Update table of contents in nnue.md

serialize.py
This PR makes small alterations to the .nnue storage format and adds support for LEB128 compression of weights (right now only for the feature transformer). An additional `--ft_compression` CLI parameter may be used when serializing a network to .nnue. Note that it's also valid to serialize from .nnue to .nnue, which can be used for compressing already existing networks. Example:
```
python serialize.py --features=HalfKAv2_hm nn-fdc1d0fe6455.nnue a.nnue --ft_compression=leb128
python serialize.py --features=HalfKAv2_hm a.nnue b.nnue --ft_compression=leb128
python serialize.py --features=HalfKAv2_hm a.nnue c.nnue
```
Now, every saved tensor may have a header, right now only present if the tensor is compressed. This header specifies the compression method used, and may contain other …
=> Support for LEB128 compression of feature transformer parameters.

docs/nnue.md
Based on https://github.com/official-stockfish/Stockfish/pull/4612
=> Add blocked sparse input affine transform approach to docs.

ftperm.py, serialize.py
This is a small rewrite of https://github.com/Ergodice/nnue-pytorch/tree/ftperm. Big thanks to @Ergodice for the great FT weight permutation optimization algorithm. I kept it as is, only reducing batch size in one place - needs revisiting later to clean up and potentially support cpu-only optimization.
`ftperm.py` can be used standalone to go through the optimization process step by step. `serialize.py` integration allows optionally including the full process (without intermediate files) to be performed during serialization. The optimization is NOT performed by default, as it takes very long and requires additional parameters.
Usage notes copied from notes in `ftperm.py`:
```
NOTE: This script uses CUDA and may requires large amounts of VRAM. Decrease --count if encountering problems. …
```
=> FT optimization utility. Integrate with serialization.

scripts/easy_train.py, scripts/easy_train_example.bat, scripts/easy_train_example.sh
Since the fishtest book was changed from `UHO_XXL_+0.90_+1.19.epd` to `UHO_4060_v2.epd` during SF16 release.
=> Update default network testing book to match new fishtest book

README.md, requirements.txt
I can split this into PRs if deemed so. The readme cleanup was kinda necessary in this scope because it was very disjoint and this patch touches the whole setup process.
I tested this on a clear venv with Python 3.11.5 on CentOS 8, running A100s.
CUDA requirement might need adjusting as time goes on and new GPUs are released, but it should at least be backwards compatible.
=> Add complete requirements.txt. Update readme on the installation process.

model.py
This was used to train a larger master net nn-ac1dbea57aa3.nnue in:
https://github.com/official-stockfish/Stockfish/pull/4795
=> Increase L1 size to 2560 for SFNNv8 nets

CMakeLists.txt, lib/nnue_training_data_formats.h
a bit better than the current approach, current approach shows up in profile with ~10% overhead
https://godbolt.org/z/avfT1jY3Y
cmake checks for zen3+ cpu
=> use pdep to find nthSetBitIndex

.gitignore, CMakeLists.txt, Dockerfile, requirements.txt, run_docker.sh, setup_script.sh, train.py
- Update CMakelists for newer cmake
- Add dockerfile for nvidia pytorch container https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch and according script to start a container
- Hide lightning dataloader warning about threads
- Update pytorch lightning to > 2
Implictly updates the cuda requirement to 12.x for the app code, your local cuda toolkit doesn't matter because the container will include everything that is required. 
Only requirement is docker and an up to date nvidia driver and NVIDIA Container Toolkit.
For driver requirements checkout of this image checkout https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-25-04.html#rel-25-04
Might break some ones training which passed additional lighnting args but I doubt that anyone recently trained anything.
=> Update Dependencies for Lightning 2 and add Dockerfile

serialize.py
right now fails with:
```
Traceback (most recent call last):
File "/workspace/scratch/77d5c41cf9e7/trainer/nnue-pytorch/serialize.py", line 361, in <module>
main()
File "/workspace/scratch/77d5c41cf9e7/trainer/nnue-pytorch/serialize.py", line 354, in main
writer = NNUEWriter(nnue, args.description, ft_compression=args.ft_compression)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/scratch/77d5c41cf9e7/trainer/nnue-pytorch/serialize.py", line 78, in __init__
self.write_feature_transformer(model, ft_compression)
File "/workspace/scratch/77d5c41cf9e7/trainer/nnue-pytorch/serialize.py", line 138, in write_feature_transformer
ascii_hist('ft bias:', bias.numpy())
^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to …
```
=> Fix serialization

serialize.py, train.py, visualize.py, visualize_multi_hist.py
In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
=> Fix Weights Loading Torch

model.py, train.py
The cudagraphs backend is a speedups for small nets, slowdown for large ones. Make it a CLI argument.
Benchmarking
big: numactl --cpunodebind=0 --membind=0 python train.py /workspace/data/dfrc_n5000.binpack\
--threads 4 --num-workers  64 --batch-size 16384 --random-fen-skipping 3\
--features=HalfKAv2_hm^ --max_epochs=4 --default_root_dir ./training/runs/run_0\
--gpus="0,"
small: big --l1=128 -compile-backend=cudagraphs
reported after epoch 3 / end of the run.
```
big                             small
master         84.99it/s, 84.57it/s          210.57it/s, 214.03it/s
PR             82.56it/s. 85.00it/s          249.80it/s, 252.89it/s
```
using cudagraphs for the big net yields:
60.27it/s, 59.24it/s
=> Enable cudagraphs compile backend
